---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/redis64
    driver:
      box: redis-box
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
